application:
  PageSize: 10
  JwtSecret: 23347$040412
  RegisterEnabled: false
  LogPath: logs/logrus.log

server:
#  RunMode: release
#  HttpPort: 8000
  RunMode: debug
  HttpPort: 9080
  ReadTimeout: 60
  WriteTimeout: 60

sessions:
  Secret: sdfmcxedsds

database:
  Type: mysql
  User: root
  Password: 123456
  Host: 127.0.0.1:3306
  Name: xhgblog
  TablePrefix: xhgblog_

oauth:
  GithubClientID:
  GithubClientSecret:
  GithubRedirectUrl:
  GithubAuthUrl: https://github.com/login/oauth/authorize?client_id=%s&scope=user:email&state=%s
  GithubTokenUrl: https://github.com/login/oauth/access_token
