application:
  PageSize: 10
  JwtSecret: 23347$040412
  RegisterEnabled: false

server:
  RunMode: debug
  #RunMode: release
  #HttpPort: 8000
  HttpPort: 9080
  ReadTimeout: 60
  WriteTimeout: 60

sessions:
  Secret: sdfmcxedsds

database:
  Type: mysql
  User: root
  Password: 123456
  Host: 127.0.0.1:3306
  Name: xhgblog
  TablePrefix: xhgblog_

oauth:
  GithubClientID: eb895a7bd1895ebe5635
  GithubClientSecret: 9e62206fbaa0a073af9a15c700da61dcfc21f252
  GithubRedirectUrl: http://localhost:9080/oauth/redirect
  GithubAuthUrl: https://github.com/login/oauth/authorize?client_id=%s&scope=user:email&state=%s
  GithubTokenUrl: https://github.com/login/oauth/access_token
